# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ernie's Leisure Code
email: b01505025@g.ntu.edu.tw
description: > # this means to ignore newlines until "baseurl:"
  Ernie Chang is a quantitative researcher specializing in high-frequency trading, market microstructure modeling, and adversarial machine learning. His work spans alpha signal development, execution modeling, and large-scale data pipeline engineering. Ernie has designed and optimized a wide range of production-grade alphas—leveraging LOB dynamics, spectral and flow-toxicity features, and federated learning frameworks—and has contributed research such as FINISH for decentralized malware detection, published in leading IEEE journals. Ernie combines rigorous academic research with practical systems engineering, building fast, reliable, and scalable analytics for real-world trading environments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ernie55ernie.github.io" # the base hostname & protocol for your site
twitter_username: b01505025
github_username:  ernie55ernie

# theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
kramdown:
    math_engine: katex

url: "https://ernie55ernie.github.io/"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

excerpt_separator: ""

include: [".well-known"]

